object Versions {

    const val coreKtx = "1.8.0"
    const val appCompat = "1.4.2"
    const val material = "1.6.1"
    const val hilt = "2.42"
    const val hiltCompiler = "2.42"
    const val timber = "5.0.1"
    const val room = "2.4.2"
    const val constraint = "2.1.4"
    const val viewModel = "2.5.1"
    const val navigation = "2.4.2"
    const val googleServices = "4.3.10"
    const val livedata = "2.5.1"
    const val gson = "2.9.0"
    const val retrofit = "2.9.0"
    const val ok_http = "5.0.0-alpha.3"
    const val coil = "1.4.0"
    const val runtime = "2.5.1"
    const val extensions = "2.2.0"
    const val safeArgs = "2.5.1"
    const val legacy = "1.0.0"
    const val junit = "4.+"
    const val testExt = "1.1.3"
    const val espresso = "3.4.0"

}